CREATE TABLE `hackathon` (
	`id` text PRIMARY KEY NOT NULL,
	`event_id` text NOT NULL,
	`team_name` text NOT NULL,
	`team_leader_name` text NOT NULL,
	`team_leader_email` text NOT NULL,
	`team_leader_phone` text NOT NULL,
	`team_leader_gender` text NOT NULL,
	`institute` text NOT NULL,
	`department` text NOT NULL,
	`year` text NOT NULL,
	`team_members` text,
	`track` text NOT NULL,
	`idea_description` text NOT NULL,
	`github_link` text,
	`previous_experience` integer NOT NULL,
	`payment_screenshot` text,
	`transaction_id` text,
	`declaration_accepted` integer NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`event_id`) REFERENCES `event`(`id`) ON UPDATE no action ON DELETE cascade
);
