import "@/styles/globals.css";

import { DM_Sans } from "next/font/google";

import Navbar from "@/components/landing/navbar";
import { UserProvider } from "@/context/userContext";
import Footer from "@/components/ui/Footer";
import { type Metadata } from "next";
import { EventProvider } from "@/context/eventContext";

const dmsans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <UserProvider>
      <EventProvider>
        <html lang="en" className={`${dmsans.variable}`}>
          <body className="space">
            <Navbar />
            {children}
            <Footer />
          </body>
        </html>
      </EventProvider>
    </UserProvider>
  );
}



