import Navbar from "@/components/landing/navbar";
import "@/styles/globals.css";

import { DM_Sans } from "next/font/google";

import { type Metadata } from "next";

const dmsans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${dmsans.variable}`}>
      <body className="space">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
