import "@/styles/globals.css";

import { DM_Sans } from "next/font/google";

import { type Metadata } from "next";

const dmsans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
        <main className="space">
          <div className="px-32 min-h-screens py-20 ">
          {children}
          </div>
        </main>
  );
}
