type TeamMember = {
  name: string;
  position: string;
  teamId: number;
  image: string;
  linkedin: string;
  Email: string;
};

type DepartmentCoordinator = {
  name: string;
  department: string;
  teamId: number;
  image: string;
  linkedin: string;
  Email: string;
};

const coreCommittee: TeamMember[] = [
  {
    teamId: 1,
    name: "Samyak Umathe",
    position: "College Coordinator\nCollege President",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3Yxs8hweLapZLNdSFOi1eyCwz342kPKltEIQr0",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 2,
    name: "V. S. Pavithra",
    position: "Club Head\nVice President",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 3,
    name: "Chirayu Patle",
    position: "Secretary & Database Head",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3YKmvvV1TRBNfpGxchseSwoU2buA0HQ3jCVYOP",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 4,
    name: "Shailaija Patle",
    position: "Secretary & Event Management Head",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3YKHOSeNTRBNfpGxchseSwoU2buA0HQ3jCVYOP",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 5,
    name: "Mansi Jalandhar",
    position: "Secretary",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3YBUmcB9dX07nFuGgApY3LIbBDVxsaiEWvk4qN",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 6,
    name: "Priyanshu Kayarkar",
    position: "Technical Head",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3YwowtJzUiYMgLRNj147yBaeFsUHhvAoqJcbdW",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 7,
    name: "Harsh Kapte",
    position: "Publicity Head",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3YRH9jwebsECkVBO3tDbHI2PpL7mWqcvT1N6KG",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 8,
    name: "Siddheshwar Madne",
    position: "Publicity Head",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 9,
    name: "Ishika Lanjewar",
    position: "Publicity Head",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3YvJsTwjcOBfKwjtA7i6CNnraLcWTPvEsD0JMH",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 10,
    name: "Aarya Kothe",
    position: "Design Head",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3Yg1eRy3FTq1JW2LQ8ZiVj3bh0NczFX7KGso9w",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 11,
    name: "Om Ingle",
    position: "Design Head",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3YTZVVuXOr7b9KQXzyCuE6BWn1l2ctFZv4gd3M",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 12,
    name: "Payal Dongre",
    position: "Literature Head",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3YLr8sqgKNvlAtR9SFIuEYU4OWr7TZ8eML5igB",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 13,
    name: "Sakshi Kadu",
    position: "Literature Head",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3Y3sECXJ5UxkNCoJRpD2yuWGnilqgjMTBm7EeX",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 14,
    name: "Sayali Padmane",
    position: "Photography Head",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3YMiRZSyJCRHOYLQvmMWn8KB1A73Jd9PwU20tp",
    linkedin: "",
    Email: "",
  },
];

const departmentalCoordinators: DepartmentCoordinator[] = [
  {
    teamId: 1,
    name: "Aliya Sayyed",
    department: "CSE",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 2,
    name: "Parth Dehare",
    department: "CSE AIML",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 3,
    name: "Muchkundraje Thote",
    department: "AIDS",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 4,
    name: "Piyush Meshram",
    department: "IT / CSD",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 5,
    name: "Saakshi Krishnani",
    department: "C-Tech",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 6,
    name: "Rudresh Bokade",
    department: "Mechanical",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 7,
    name: "Sakshi Vairagade",
    department: "ETC / VLSI / IOT / EE",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 8,
    name: "Khushi Chaudhari",
    department: "Electrical",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 9,
    name: "Charvi Kadbe",
    department: "Civil",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
];

// Keep the old teamMembers array for backward compatibility
const teamMembers = coreCommittee;

const SecondYear: TeamMember[] = [
  {
    teamId: 1,
    name: "Aliya Sayyed",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 2,
    name: "Gauri Ganeshrao Lokhande",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 3,
    name: "Harsh Kapte",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 4,
    name: "Manasvi Totewar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 5,
    name: "Mayur Rasik Buddhe",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 6,
    name: "Milind Anil Late",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 7,
    name: "Saakshi Krishnani",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 8,
    name: "Sakshi Vairagade",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 9,
    name: "Sandesh Pakhidde",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 10,
    name: "Shraddha Dinesh Shingnapure",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 11,
    name: "Shravani Prashant Aney",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 12,
    name: "Aditya Rajendra Thakare",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 13,
    name: "Aarya Kothe",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 14,
    name: "Charvi Kadbe",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 15,
    name: "Dnyanata Wakode",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 16,
    name: "Ishika Lanjewar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 17,
    name: "Mansi Jalandhar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 18,
    name: "Muchkundraje Thote",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 19,
    name: "Rutuja Nareshrao Gondane",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 20,
    name: "Bhagyashri Vaidya",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 21,
    name: "Sanskruti Sanjay Moundekar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 22,
    name: "Sujal Sawalkar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 23,
    name: "Akanksha Sawant",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 24,
    name: "Parth Dehare",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 25,
    name: "Rudresh Bokade",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 26,
    name: "Himanshu Chaudhari",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 27,
    name: "Lavanya Ukey",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 28,
    name: "Samyak Umathe",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 29,
    name: "Soukhya Sasankar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 30,
    name: "Aman Kolhe",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 31,
    name: "Prathamesh Mandhane",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 32,
    name: "Vidhi Lonarkar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 33,
    name: "Parth Dhurve",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 34,
    name: "Vedang Kulkarni",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 35,
    name: "Sia Khurana",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 36,
    name: "Shailaja Patle",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 37,
    name: "Sayali Padmane",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 38,
    name: "Khushi Chaudhary",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 39,
    name: "Anandi Thakre",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 40,
    name: "Divya Dhule",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 41,
    name: "Payal Dongre",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 42,
    name: "Muskan Dhengre",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
];

const ThirdYear: TeamMember[] = [
  {
    teamId: 1,
    name: "Aastha Chilbilwar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 2,
    name: "Aditya Dharpure",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 3,
    name: "Atharva Pophali",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 4,
    name: "Dnyaneshwar Itankar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 5,
    name: "Himanshi Bakde",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 6,
    name: "Himanshu Kukde",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 7,
    name: "Janhvi Parshivnikar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 8,
    name: "Laxmikant Sanjay Dhawade",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 9,
    name: "Lokesh Dhurve",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 10,
    name: "Malay Lokhande",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 11,
    name: "Om Bhate",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 12,
    name: "Om Rajulwar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 13,
    name: "Piyush Piprewar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 14,
    name: "Pragati Wange",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 15,
    name: "Prathmesh Somkuwar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 16,
    name: "Pratik Borkar",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 17,
    name: "Rewant Chaudhari",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 18,
    name: "Romi Pun",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 19,
    name: "Sakshi Gedam",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 20,
    name: "Sejula Chopde",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 21,
    name: "Shivam Saraf",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 22,
    name: "Surbhi Ninave",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 23,
    name: "Swastika Tinkhede",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 24,
    name: "Ujjwal Bokde",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 25,
    name: "Vaideesh Deshmukh",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 26,
    name: "Vanshvardhan Sorte",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
  {
    teamId: 27,
    name: "Virendra Lokhande",
    position: "Member",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "",
    Email: "",
  },
];

const Devlopers: TeamMember[] = [
  {
    teamId: 1,
    name: "Priyanshu Kayarkar",
    position: "Co-ordinator",
    image: "https://xxdyayurwn.ufs.sh/f/U6UD7bkQZy3YwowtJzUiYMgLRNj147yBaeFsUHhvAoqJcbdW",
    linkedin: "https://www.linkedin.com/in/priyanshukayarkar",
    Email: "priyanshu.kayarkar009@gmail.com",
  },
  {
    teamId: 2,
    name: "Chirayu Patle",
    position: "Co-ordinator",
    image:
      "https://res.cloudinary.com/priyanshukayarkar/image/upload/v1753200516/chiryu_a91uyo.jpg",
    linkedin: "https://www.linkedin.com/in/chirayu-patle-a78502290/",
    Email: "chirayupatle2@gmail.com",
  },
  {
    teamId: 3,
    name: "Muchkundraje Thote",
    position: "Co-ordinator",
    image:
      "https://res.cloudinary.com/priyanshukayarkar/image/upload/v1753201045/much-org-1_xp2amh.jpg",
    linkedin: "https://www.linkedin.com/in/muchkund-thote/",
    Email: "muchkundthote@gmail.com",
  },
  {
    teamId: 4,
    name: "Samyak Umathe",
    position: "Co-ordinator",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
    linkedin: "https://www.linkedin.com/in/samyak-umathe-9b8a6a295/",
    Email: "samyakumathe@gmail.com",
  },
];
export { coreCommittee, departmentalCoordinators, teamMembers, Devlopers, SecondYear, ThirdYear };
