type TeamMember = {
  name: string;
  position: string;
  teamId: number;
  image: string;
};

const teamMembers: TeamMember[] = [
  {
    teamId: 1,
    name: "Laxmikant Dhawade",
    position: "College Co-ordinator",
    image: "/image/ust-event2.JPG",
  },
  {
    teamId: 2,
    name: "Swastika Tinkhede",
    position: "Club Head",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 3,
    name: "Virendra Lokhande",
    position: "Secretary",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 4,
    name: "Piyush Piprewar",
    position: "Database Head",
    image:
      "https://hmrvazaoddsexmrgydqx.supabase.co/storage/v1/object/sign/Engineering-India-Storage/Leads-Images/PiyushPiprewar.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJFbmdpbmVlcmluZy1JbmRpYS1TdG9yYWdlL0xlYWRzLUltYWdlcy9QaXl1c2hQaXByZXdhci5wbmciLCJpYXQiOjE3NDMyNzQ0MTIsImV4cCI6MjA1ODYzNDQxMn0.902TUHwkaODtcPHrOF5of3f6OFmzpt34tWaaGMRTLeI",
  },
  {
    teamId: 5,
    name: "Jahanvi Parshivninkar",
    position: "Secretary - Event Management",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 6,
    name: "Ujwal Bokde",
    position: "Secretary - Technical Head",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 7,
    name: "Himanshu Kukde",
    position: "Secretary - Publicity Head",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 8,
    name: "Surbhi Ninawe",
    position: "Secretary - Other Colleges Co-ordination",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 9,
    name: "Sejula Chopde",
    position: "Joint Secretary",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 10,
    name: "Shivam Saraf",
    position: "Social Media and Photography Head",
    image:
      "https://hmrvazaoddsexmrgydqx.supabase.co/storage/v1/object/sign/Engineering-India-Storage/Leads-Images/Shivam.jpeg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJFbmdpbmVlcmluZy1JbmRpYS1TdG9yYWdlL0xlYWRzLUltYWdlcy9TaGl2YW0uanBlZyIsImlhdCI6MTc0MzI3NDQ2NywiZXhwIjoyMDU4NjM0NDY3fQ.4qjT5LmXOhn8EPnLLu-T6N-ZuYof9LVJZsSlWiyGBb4",
  },
  {
    teamId: 11,
    name: "Astha Chilbilwar",
    position: "Design Head",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 12,
    name: "Malay Lokhande",
    position: "Design Head",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 13,
    name: "Vanshvardhan Sorte",
    position: "Public Relation and Event Management Head",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 14,
    name: "Pragati Wange",
    position: "Literature Head",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 15,
    name: "Sakshi Gedam",
    position: "Literature Head",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 16,
    name: "Romi Pun",
    position: "IT Co-ordinator",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 17,
    name: "Vaideesh Deshmukh",
    position: "CSE Departmental Co-ordinator",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 18,
    name: "Pratik Borkar",
    position: "Mechanical Department Co-ordinator",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 19,
    name: "Rewant Chaudhari",
    position: "ETC Departmental Co-ordinator",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 20,
    name: "Atharva Pophali",
    position: "C-Tech Departmental Co-ordinator",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
];
const SecondYear = [
  { teamId: 1, name: "Aliya Sayyed", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 2, name: "Gauri Ganeshrao Lokhande", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 3, name: "Harsh Kapte", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 4, name: "Manasvi Totewar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 5, name: "Mayur Rasik Buddhe", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 6, name: "Milind Anil Late", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 7, name: "Saakshi Krishnani", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 8, name: "Sakshi Vairagade", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 9, name: "Sandesh Pakhidde", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 10, name: "Shraddha Dinesh Shingnapure", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 11, name: "Shravani Prashant Aney", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 12, name: "Aditya Rajendra Thakare", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 13, name: "Aarya Kothe", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 14, name: "Charvi Kadbe", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 15, name: "Dnyanata Wakode", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 16, name: "Ishika Lanjewar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 17, name: "Mansi Jalandhar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 18, name: "Muchkundraje Thote", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 19, name: "Rutuja Nareshrao Gondane", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 20, name: "Bhagyashri Vaidya", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 21, name: "Sanskruti Sanjay Moundekar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 22, name: "Sujal Sawalkar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 23, name: "Akanksha Sawant", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 24, name: "Parth Dehare", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 25, name: "Rudresh Bokade", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 26, name: "Himanshu Chaudhari", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 27, name: "Lavanya Ukey", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 28, name: "Samyak Umathe", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 29, name: "Soukhya Sasankar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 30, name: "Aman Kolhe", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 31, name: "Prathamesh Mandhane", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 32, name: "Vidhi Lonarkar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 33, name: "Parth Dhurve", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 34, name: "Vedang Kulkarni", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 35, name: "Sia Khurana", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 36, name: "Shailaja Patle", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 37, name: "Sayali Padmane", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 38, name: "Khushi Chaudhary", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 39, name: "Anandi Thakre", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 40, name: "Divya Dhule", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 41, name: "Payal Dongre", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 42, name: "Muskan Dhengre", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" }
];

const ThridYear: TeamMember[]  = [
  { teamId: 1, name: "Aastha Chilbilwar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 2, name: "Aditya Dharpure", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 3, name: "Atharva Pophali", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 4, name: "Dnyaneshwar Itankar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 5, name: "Himanshi Bakde", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 6, name: "Himanshu Kukde", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 7, name: "Janhvi Parshivnikar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 8, name: "Laxmikant Sanjay Dhawade", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 9, name: "Lokesh Dhurve", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 10, name: "Malay Lokhande", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 11, name: "Om Bhate", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 12, name: "Om Rajulwar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 13, name: "Piyush Piprewar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 14, name: "Pragati Wange", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 15, name: "Prathmesh Somkuwar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 16, name: "Pratik Borkar", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 17, name: "Rewant Chaudhari", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 18, name: "Romi Pun", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 19, name: "Sakshi Gedam", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 20, name: "Sejula Chopde", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 21, name: "Shivam Saraf", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 22, name: "Surbhi Ninave", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 23, name: "Swastika Tinkhede", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 24, name: "Ujjwal Bokde", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 25, name: "Vaideesh Deshmukh", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 26, name: "Vanshvardhan Sorte", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" },
  { teamId: 27, name: "Virendra Lokhande", position: "Member", image: "https://cdn-icons-png.flaticon.com/128/456/456212.png" }
] 
const Devlopers: TeamMember[] = [
  {
    teamId: 1,
    name: "Priyanshu Kayarkar",
    position: "College Co-ordinator",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 2,
    name: "Chirayu Patel",
    position: "Club Head",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 3,
    name: "Muchkundraje Thote",
    position: "Secretary",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
  {
    teamId: 4,
    name: "SAMYAK UMATHE",
    position: "Secretary",
    image: "https://cdn-icons-png.flaticon.com/128/456/456212.png",
  },
];
export { teamMembers, SecondYear, ThridYear, Devlopers };
